Cal/fatlib migration
mlp6/ADPL pull request #226
Opened 2017-07-05 18:35 UTC by CalNightingale

Adds SD card data support

2017-07-05 20:25 UTC, mlp6 requested changes

2017-07-05 20:25 UTC, mlp6 commented on software/ADPL_electron/ADPL_electron.ino
> +#include "pin_mapping.h"
@CalNightingale it appears that `pin_mapping.h` is included regardless of the value of `sdIsInstalled`; can we move that outside the `if/else` structure, or is that required to get things to compile?  I would guess it should be able to be moved out... was this the error that you encountered before?

2017-07-05 20:25 UTC, mlp6 commented on software/ADPL_electron/ADPL_electron.ino
> +bool sDSuccess = false;
Do we still need this variable?

2017-07-05 20:56 UTC, CalNightingale commented on software/ADPL_electron/ADPL_electron.ino
> +#include "pin_mapping.h"
Yes. Because (no idea why) an error is thrown if `pin_mapping.h` is included before including both publishing methods, this redundancy is necessary

2017-07-05 20:58 UTC, CalNightingale commented on software/ADPL_electron/ADPL_electron.ino
> +bool sDSuccess = false;
Nope! I have removed it and made another commit.

2017-07-06 01:58 UTC, mlp6 submitted a review, later dismissed

2017-08-25 21:18 UTC, mlp6 reviewed
Waiting for Graham's testing on the device before merging in.

2017-08-30 19:52 UTC, mlp6 approved these changes
Graham has tested all of these changes on the current hardware setup going to the Philippines.

2017-08-30 20:00 UTC, merged