Cal/ctrl batch flow
mlp6/ADPL pull request #229
Opened 2017-07-06 17:26 UTC by CalNightingale

Refactors the pinch valve field patch

2017-07-07 16:28 UTC, mlp6 requested changes
@CalNightingale a few comments for your consideration

2017-07-07 16:28 UTC, mlp6 commented on software/ADPL_electron/ADPL_electron.ino
> +            pinchValve.down = true;
@CalNightingale do we need both `pinchValve.up` and `pingValve.down` (i.e., is one always opposite the other?  if so, then no need for both... but if both could be `false`, or something like that, then maybe both are needed).

2017-07-07 16:28 UTC, mlp6 commented on software/ADPL_electron/ADPL_electron.ino
> +    pinchValve.wait_time = 0;
@CalNightingale what does `wait_time` actually represent?  maybe this could be renamed to be a bit more explicit in its use.

2017-07-07 16:28 UTC, mlp6 commented on software/ADPL_electron/ADPL_electron.ino
>  #define MAX_POSITION 5.0 // in mm
@CalNightingale do we still need `MAX_POSITION` and `MIN_POSITION`?

2017-07-07 18:01 UTC, CalNightingale commented on software/ADPL_electron/ADPL_electron.ino
>  #define MAX_POSITION 5.0 // in mm
We don't! I have removed them.

2017-07-07 18:21 UTC, CalNightingale commented on software/ADPL_electron/ADPL_electron.ino
> +    pinchValve.wait_time = 0;
It represents the last time the pinch valve was moved. I have changed it's name to lastTime, which is consistent with the syntax of the bucket (which has a similar variable)

2017-07-07 18:31 UTC, CalNightingale commented on software/ADPL_electron/ADPL_electron.ino
> +            pinchValve.down = true;
We don't need both; I have removed `pinchValve.down` and replaced it with `!pinchValve.up` in all locations and wherever `pinchValve.down` was set, `pinchValve.up` is now set to the opposite value

2017-07-07 18:33 UTC, CalNightingale commented
Before committing this, I think it would be a good idea to test it on a working setup, since we currently have no idea whether it works as expected. Is there such a setup somewhere around here that I could test this code on?

2017-07-09 02:05 UTC, mlp6 commented
They will have a setup that you can test on.  Both @aforbis-stokes and Graham will be back in the country next week and can help you with this.  You can commit things to this branch... just no merging until tested.

2017-07-12 18:58 UTC, mlp6 commented
@CalNightingale has this been adequately tested, or are you planning to do more?

2017-08-25 21:09 UTC, closed without merging

2017-08-25 21:10 UTC, mlp6 commented
This branch is outdated and certain changes were manually cherry picked onto the `cal/fatlibMigration` branch.